CREATE INDEX IDX_PROB_SLUG ON PROBLEMS(SLUG);
CREATE INDEX IDX_PROB_DIFFICULTY ON PROBLEMS(DIFFICULTY);

CREATE INDEX IDX_EXAMPLES_PROB_ID ON PROBLEM_EXAMPLES(PROBLEM_ID);
CREATE INDEX IDX_CONS_PROB_ID ON PROBLEM_CONSTRAINTS(PROBLEM_ID);
CREATE INDEX IDX_HINTS_PROB_ID ON PROBLEM_HINTS(PROBLEM_ID);

CREATE INDEX IDX_SOL_PROB_ID ON PROBLEM_SOLUTIONS(PROBLEM_ID);
CREATE INDEX IDX_CODE_SOL_ID ON SOLUTION_CODE(SOLUTION_ID);
